routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes(["register" => false, "reset" => false]);

Route::get('/', "HomeController@index")->middleware("auth")->name("home");

/*Client*/
Route::resource("client", "ClientController")->except(["show", "destroy"]) -> middleware("auth");
Route::group(['prefix' => "client", 'as' => 'client.', "middleware" => "auth"], function () {
    Route::get("destroy/{id}", "ClientController@destroy")->where(["id" => "[0-9]+"])->name("destroy");
    Route::get("monthly-services-form/{id}", "ClientController@monthlyServicesForm")
        ->where(["id" => "[0-9]+"])
        ->name("monthlyServicesForm");

    Route::post("monthly-services-add/{id}", "ClientController@monthlyServicesAdd")
        ->where(["id" => "[0-9]+"])
        ->name("monthlyServicesAdd");

    Route::get("monthly-services-delete/{id}/{services_item_id}", "ClientController@monthlyServicesDelete")
        ->where(["id" => "[0-9]+"])
        ->where(["services_item_id" => "[0-9]+"])
        ->name("monthlyServicesDelete");
});

/*Services*/
Route::group(['prefix' => "services", 'as' => 'services.', "middleware" => "auth"], function () {
    Route::get("import", "ServicesItemController@formImport")->name("formImport");
    Route::post("import", "ServicesItemController@import")->name("import");

    /*ServicesItem*/
    Route::resource("item", "ServicesItemController")->except(["show", "destroy"]);
    Route::group(['prefix' => "item", 'as' => 'item.', "middleware" => "auth"], function () {
        Route::get("destroy/{id}", "ServicesItemController@destroy")->where(["id" => "[0-9]+"])->name("destroy");
    });

    /**
     * ServiceGroup
     */
    Route::resource("group", "ServicesGroupController")->except(["show", "destroy"]);
    Route::group(['prefix' => "group", 'as' => 'group.', "middleware" => "auth"], function () {
        Route::get("destroy/{id}", "ServicesGroupController@destroy")->where(["id" => "[0-9]+"])->name("destroy");
    });

    Route::post("getServicesItem", "ServicesItemController@getServicesItem")->name("getServicesItem");
    Route::post("getServicesItemByClientId", "ServicesItemController@getServicesItemByClientId")->name("getServicesItemByClientId");
    Route::post("getServicesGroupByClientId", "ServicesGroupController@getServicesGroupByClientId")->name("getServicesGroupByClientId");
});

/*Job-log*/
Route::group(['prefix' => "job-log", 'as' => 'job_log.', "middleware" => "auth"], function () {
    Route::get("show", "JobLogController@index")->name("index")->middleware("job_log.dataTable.defaultFilter");
    Route::get("create", "JobLogController@create")->name("create");
    Route::post("store", "JobLogController@store")->name("store");
    Route::get("update/{id}", "JobLogController@edit")->name("edit");
    Route::post("update/{id}", "JobLogController@update")->name("update");
    Route::get("delete/{id}", "JobLogController@delete")->name("delete");
    Route::post("getJobByProject", "JobLogController@getJobByProject")->name("getJobByProject");

    Route::post("calcTotalAjax", "JobLogController@calcTotalAjax")->name("calcTotalAjax");
    Route::post("checkMonthlyJobByClientId", "JobLogController@checkMonthlyJobByClientId") -> name("checkMonthlyJobByClientId");
    Route::get("add-monthly-job-by-client-id/{client_id}", "JobLogController@addMonthlyJobByClientId")
        -> where(["client_id" => "[0-9]+"])
        -> name("addMonthlyJobByClientId");

    Route::group(["prefix" => "reporting", "as" => "reporting."], function () {
        Route::get("build", "JobLogReport\BuildReportController@build")->name("build");
        Route::get("export-report", "JobLogReport\BuildReportController@exportReport")->name("exportReport");

        /**
         * Звіти для бухгалтерії
         */
        Route::group(["prefix" => "accounting", "as" => "accounting."], function () {
            Route::get("/", "JobLogReport\AccountingReportsController@index")->name("index");
            Route::get("get-added-services/{client_id}/{month}", "JobLogReport\AccountingReportsController@getAddedServices")
                ->where(["client_id" => "[0-9]+"])
                ->name("getAddedServices");
            Route::post("download-report", "JobLogReport\AccountingReportsController@downloadReport")->name("downloadReport");
        });

    });
});

/*Translations*/
Route::resource("translations", "Translation\TranslationsController")->except(["show", "destroy"]) -> middleware("auth");
Route::group(['prefix' => "translations", 'as' => 'translations.', "middleware" => "auth"], function () {
    Route::get("destroy/{id}", "Translation\TranslationsController@destroy")->where(["id" => "[0-9]+"])->name("destroy");
});

/*Project*/
Route::resource("project", "ProjectController")->except(["show", "destroy", "store"]) -> middleware("auth");
Route::group(["prefix" => "project", "as" => "project.", "middleware" => "auth"], function () {
    Route::post("storeAjax", "ProjectController@storeAjax")->name("storeAjax");
    Route::get("close/{id}", "ProjectController@close")
        ->where(["id" => "[0-9]+"])
        ->name("close");
    Route::get("destroy/{id}", "ProjectController@destroy")
        ->where(["id" => "[0-9]+"])
        ->name("destroy");
    Route::get("details-info/{id}", "ProjectController@details_info")
        ->where(["id" => "[0-9]+"])
        ->name("details_info");
});

/**
 * Coefficient
 */
Route::resource("coefficient", "CoefficientController")->except(["show", "destroy"]) -> middleware("auth");
Route::group(["prefix" => "coefficient", "as" => "coefficient.", "middleware" => "auth"], function () {
    Route::get("destroy/{id}", "CoefficientController@destroy")
        ->where(["id" => "[0-9]+"])
        ->name("destroy");
});


/**
 * Users
 */
Route::resource("users", "UsersController")->except(["show", "destroy"]) -> middleware("auth");
Route::group(["prefix" => "users", "as" => "users.", "middleware" => "auth"], function () {
    Route::get("reset-password/{id}", "UsersController@resetPasswordForm")
        ->where(["id" => "[0-9]+"])
        ->name("resetPasswordForm");
    Route::post("reset-password/{id}", "UsersController@resetPassword")
        ->where(["id" => "[0-9]+"])
        ->name("resetPassword");
    Route::get("destroy/{id}", "UsersController@destroy")
        ->where(["id" => "[0-9]+"])
        ->name("destroy");
});

/**
 * Units
 */
Route::resource("units", "UnitsController")->except(["show", "destroy"]) -> middleware("auth");
Route::group(["prefix" => "units", "as" => "units.", "middleware" => "auth"], function () {
    Route::get("destroy/{id}", "UnitsController@destroy")
        ->where(["id" => "[0-9]+"])
        ->name("destroy");
});


Route::group(["prefix" => "zkaccess", "as" => "zkaccess.", "middleware" => "auth"], function () {
    Route::get("/", "ZKAccess\ZKAccessController@index")->name("index");
    Route::post("get-report", "ZKAccess\ZKAccessController@getReport")->name("getReport");
});

Route::group(["prefix" => "accounting", "as" => "accounting.", "middleware" => "auth"], function () {

    Route::group(["prefix" => "delivery", "as" => "delivery."],  function () {
        Route::get("/", "Accounting\DeliveryController@index") -> name("index");

        Route::get("by-qr", "Accounting\DeliveryController@byQr") -> name("byQr");

        Route::get("by-product-id/{product_id}", "Accounting\DeliveryController@byProductId") -> where(["product_id" => "[0-9]+"]) -> name("byProductId");
        Route::post("delivery-store", "Accounting\DeliveryController@deliveryStore") -> name("deliveryStore");
        Route::get("getClientWorkerByClientId/{client_id}", "Accounting\DeliveryController@getClientWorkerByClientId") -> name("getClientWorkerByClientId");

    });

    Route::group(["prefix" => "cartridge", "as" => "cartridge."], function () {
        Route::get("/", "Accounting\CartridgeAccountingController@index") -> name("index");
        Route::get("delivery-by-qr", "Accounting\CartridgeAccountingController@deliveryByQr") -> name("deliveryByQr");

        Route::get("delivery-by-product-id/{product_id}", "Accounting\CartridgeAccountingController@deliveryByProductId")
            -> where(["product_id" => "[0-9]+"])
            -> name("delivery-by-product-id");
    });
});

app/Http/Controllers/ProjectController.php
<?php

namespace App\Http\Controllers;

use App\Forms\ProjectForm;
use App\Helpers\ControllerHelper;
use App\Model\Projects;
use App\Repository\JobLogRepository;
use App\Repository\ProjectRepository;
use App\Repository\RegistryRepository;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use Kris\LaravelFormBuilder\FormBuilder;
/**
 * Class ProjectController
 * @package App\Http\Controllers
 */
class ProjectController extends Controller
{
    use ControllerHelper;

    /**
     * @var ProjectRepository
     */
    private $ProjectRepository;

    /**
     * @var JobLogRepository
     */
    private $JobLogRepository;

    public function __construct()
    {
        $this->ProjectRepository = app(ProjectRepository::class);
        $this->JobLogRepository = app(JobLogRepository::class);

    }


    /**
     * @param FormBuilder $formBuilder
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index(FormBuilder $formBuilder)
    {
        $formCreateProject = $formBuilder->create(ProjectForm::class, [
            "attr" => [
                "id" => "formCreateProject"
            ]
        ]);

        return view("projects.index", [
            "title" => __("page.project.showAll.title"),
            "table_id" => "project_data_table",
            "card_title" => __("page.project.showAll.title"),
            "projectDataTable" => $this->ProjectRepository->getAll(),
            "formCreateProject" => $formCreateProject,
        ]);
    }

    /**
     * @param Request $request
     * @return \Illuminate\Http\JsonResponse
     */
    public function storeAjax(Request $request)
    {
        $validation = Validator::make($request->input(), ["name" => "required|unique:projects,name"]);

        if ($validation->passes()) {
            $ProjectModel = new Projects();
            $result = $ProjectModel->store($request->input());
            return response()->json(["result" => $result]);
        } else {
            return response()->json($validation->errors()->all(), 422);
        }
    }

    /**
     * @param $id
     * @param FormBuilder $formBuilder
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit($id, FormBuilder $formBuilder)
    {
        $formData = $this->ProjectRepository->getForEdit($id);
        $form = $formBuilder->create(ProjectForm::class, [
            "method" => "PUT",
            "url" => route("project.update", $id),
            "model" => $formData
        ]);

        $form->add("submit", "submit", ["label" => __("basic.label.save"), "attr" => ["class" => "form-control btn-success"]]);

        return view("layouts.simples.simple_form",
            [
                "form" => $form,
                "title" => __("page.client.edit"),
                "card_title" => __("page.client.edit"),
            ]
        );
    }

    /**
     * @param $id
     * @param Request $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update($id, Request $request)
    {
        Validator::make($request->input(), ["name" => "required|unique:projects,name,$id"])->validate();
        $ProjectModel = new Projects();
        $result = $ProjectModel->store($request->except(["_token"]), $id);

        return $this->resultRedirect($result);
    }

    /**
     * @param $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy($id)
    {
        $result = Projects::where("id", $id)->delete();

        return ($result)
            ? redirect()->route("project.index")->with("message", __("basic.messages.success"))
            : redirect()->route("project.index")->withErrors([__("basic.messages.error")]);
    }

    /**
     * @param $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function close($id)
    {
        $ProjectModel = new Projects();
        $result = $ProjectModel->closeProject($id);

        return $this->resultRedirect($result);
    }

    /**
     * @param $id
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function details_info($id) {
        $dataTable = $this->JobLogRepository->getByProjectId($id);
        $project = $this->ProjectRepository->getForEdit($id);

        return view("projects.details_info", [
            "title" => "Виконанні роботи за проектом - ".$project->name,
            "card_title" => "Виконанні роботи за проектом - <strong>".$project->name."</strong>",
            "dataTable" => $dataTable,
            "total" => $dataTable->sum("total_price"),
            "total_pdv" => $this->JobLogRepository->calc_pdv($dataTable->sum("total_price")),
            "project_info" => $project
        ]);
    }


}

resources/views/projects/details_info.blade.php
@extends("layouts.data_table")
@section("control_card")
    @if(!$project_info->is_close)
        <button data-href="{{route("project.close", $project_info->id)}}" class="btn btn-warning closeProject" title="{!! __("page.project.showAll.label.project_close") !!}"><i class="fa fa-times"></i> {!! __("page.project.showAll.label.project_close") !!}</button>
    @else
        <a href="{{route("project.close", $project_info->id)}}" class="btn btn-warning" title="{!! __("page.project.showAll.label.project_open") !!}"><i class="fa fa-circle"></i> {!! __("page.project.showAll.label.project_open") !!}</a>
    @endif

    <button data-href="{{route("project.destroy", $project_info->id)}}" title="Видалити" class="btn btn-danger deleteProject"  ><i class="fa fa-trash"></i>  {!! __("page.basic.label.delete") !!}</button>
@endsection

@section("table_header")
    <tr>
        {{--<th>{!! __("form.project.attr.isClose") !!}</th>--}}
        <th></th>
        <th>Назва послуги</th>
        <th>Ціна</th>
        <th>Кількість</th>
        <th>Коефіцієнт</th>
        <th>Сума</th>
        <th>Створив користувач</th>
        <th>Виконавці</th>
        <th>Дата</th>
        <th>Створенно</th>
    </tr>
@endsection

@section("table_body")
    @foreach($dataTable as $item)
        <tr>
            <td>
                @if(!$item->project_is_close)
                    <a href="{{route("job_log.edit", "$item->id")}}" title="{!! __("page.basic.label.edit") !!}" class="btn btn-sm btn-warning"><i class="fa fa-edit"></i></a>
                @endif
            </td>
            <td>
                <a href="{{route("services.item.edit", $item->services_item_id )}}" title="{!! $item->services_item_name !!}" target="_blank">
                    {{ \Illuminate\Support\Str::limit($item->services_item_name, 50, "...") }}
                </a>
            </td>
            <td>{!! $item->price !!}</td>
            <td>{!! $item->count !!}</td>
            <td>{!! $item->coefficient !!}</td>
            <td>{!! $item->total_price !!}</td>
            <td>{!! $item->user_creator !!}</td>
            <td>{{$item->user_exec_name}}</td> {{--App\Model\JobLog->getUserExecNameAttribute() --}}
            <td>{!! $item->date_time !!}</td>
            <td>{!! $item->created_at !!}</td>
        </tr>
    @endforeach
@endsection

@section("table_footer")
    <tr>
        <th colspan="4">Підсумок:</th>
        <th colspan="2">Сума:</th>
        <th>{!! $total !!}</th>
        <th colspan="2">Сума з ПДВ:</th>
        <th>{!! $total_pdv !!}</th>
    </tr>
@endsection


@section("js")
    @parent
    <script>
        $(".deleteProject").on("click", function () {
            let href = $(this).attr("data-href");
            scripts.confirmDeleteItemByHref(href, "Увага", "Ви впевненні що хочете видалити цей проект?")
        })

        $(".closeProject").on("click", function () {
            let href = $(this).attr("data-href");
            scripts.confirmDeleteItemByHref(href, "Увага", "Ви впевненні що хочете закрити цей проект?", 'Закрити')
        })
    </script>
@stop

resources/views/projects/index.blade.php
@extends("layouts.data_table", ["table_classes" => "table table-striped projects", "nowrap" => false])

@section("content")
    @parent
    @include("projects.modal_create_project")
@stop

@section("control_card")
    <button type="button" class="btn btn-success" data-toggle="modal" data-target="#modal-default"> <i class="fa fa-plus"></i>  {!! __("basic.label.add") !!}</button>
@endsection

@section("table_header")
    <tr>
        <th>{!! __("form.base.attr.name") !!}</th>
        <th>Статус проекту</th>
        <th>{!! __("form.base.attr.updated") !!}</th>
        <th></th>
    </tr>
@endsection

@section("table_body")
    @foreach($projectDataTable as $item)
        <tr>
            <td> {{--{!! $item->name !!} --}}

                <a>
                    {!! $item->name !!}
                </a>
                <br/>
                <small>
                    {!! __("form.base.attr.created") !!}:
                    {!! $item->created_at !!}
                </small>
            </td>
            <td>
                @if(!$item->is_close)
                    <span class="badge badge-success">Проект в роботі</span>
                @else
                    <span class="badge badge-warning">{!! __("form.project.attr.isClose") !!}</span>
                @endif
            </td>
            <td> {!! $item->updated_at !!} </td>

            <td class="project-actions text-right">
                <a href="{{route("project.edit", $item->id)}}" class="btn btn-info btn-sm" title="{!! __("page.basic.label.edit") !!}">
                    <i class="fa fa-edit"></i>
                    Редагувати
                </a>
                <a href="{{route("project.details_info", $item->id)}}" class="btn btn-primary btn-sm" title="Детальніше">
                    <i class="fas fa-folder"></i>
                    Детальніше
                </a>
            </td>

        </tr>
    @endforeach
@endsection

@section("table_footer")
    <tr>
        <th>{!! __("form.base.attr.name") !!}</th>
        <th>Статус проекту</th>
        <th>{!! __("form.base.attr.updated") !!}</th>
        <th></th>
    </tr>
@endsection

resources/views/projects/modal_create_project.blade.php
<div class="modal fade" id="modal-default">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">{!! __("page.project.create.title") !!}</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                {!! form($formCreateProject) !!}
            </div>
            <div class="modal-footer justify-content-between">
                <button type="button" class="btn btn-default" data-dismiss="modal" >{!! __("form.base.attr.cancel") !!}</button>
                <button type="button" class="btn btn-primary" id="btnCreateProject">{!! __("basic.label.save") !!}</button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>

@section("js")
    @parent
    {{Html::script("js/components/project/project.js")}}
@stop