routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes(["register" => false, "reset" => false]);

Route::get('/', "HomeController@index")->middleware("auth")->name("home");

/*Client*/
Route::resource("client", "ClientController")->except(["show", "destroy"]) -> middleware("auth");
Route::group(['prefix' => "client", 'as' => 'client.', "middleware" => "auth"], function () {
    Route::get("destroy/{id}", "ClientController@destroy")->where(["id" => "[0-9]+"])->name("destroy");
    Route::get("monthly-services-form/{id}", "ClientController@monthlyServicesForm")
        ->where(["id" => "[0-9]+"])
        ->name("monthlyServicesForm");

    Route::post("monthly-services-add/{id}", "ClientController@monthlyServicesAdd")
        ->where(["id" => "[0-9]+"])
        ->name("monthlyServicesAdd");

    Route::get("monthly-services-delete/{id}/{services_item_id}", "ClientController@monthlyServicesDelete")
        ->where(["id" => "[0-9]+"])
        ->where(["services_item_id" => "[0-9]+"])
        ->name("monthlyServicesDelete");
});

/*Services*/
Route::group(['prefix' => "services", 'as' => 'services.', "middleware" => "auth"], function () {
    Route::get("import", "ServicesItemController@formImport")->name("formImport");
    Route::post("import", "ServicesItemController@import")->name("import");

    /*ServicesItem*/
    Route::resource("item", "ServicesItemController")->except(["show", "destroy"]);
    Route::group(['prefix' => "item", 'as' => 'item.', "middleware" => "auth"], function () {
        Route::get("destroy/{id}", "ServicesItemController@destroy")->where(["id" => "[0-9]+"])->name("destroy");
    });

    /**
     * ServiceGroup
     */
    Route::resource("group", "ServicesGroupController")->except(["show", "destroy"]);
    Route::group(['prefix' => "group", 'as' => 'group.', "middleware" => "auth"], function () {
        Route::get("destroy/{id}", "ServicesGroupController@destroy")->where(["id" => "[0-9]+"])->name("destroy");
    });

    Route::post("getServicesItem", "ServicesItemController@getServicesItem")->name("getServicesItem");
    Route::post("getServicesItemByClientId", "ServicesItemController@getServicesItemByClientId")->name("getServicesItemByClientId");
    Route::post("getServicesGroupByClientId", "ServicesGroupController@getServicesGroupByClientId")->name("getServicesGroupByClientId");
});

/*Job-log*/
Route::group(['prefix' => "job-log", 'as' => 'job_log.', "middleware" => "auth"], function () {
    Route::get("show", "JobLogController@index")->name("index")->middleware("job_log.dataTable.defaultFilter");
    Route::get("create", "JobLogController@create")->name("create");
    Route::post("store", "JobLogController@store")->name("store");
    Route::get("update/{id}", "JobLogController@edit")->name("edit");
    Route::post("update/{id}", "JobLogController@update")->name("update");
    Route::get("delete/{id}", "JobLogController@delete")->name("delete");
    Route::post("getJobByProject", "JobLogController@getJobByProject")->name("getJobByProject");

    Route::post("calcTotalAjax", "JobLogController@calcTotalAjax")->name("calcTotalAjax");
    Route::post("checkMonthlyJobByClientId", "JobLogController@checkMonthlyJobByClientId") -> name("checkMonthlyJobByClientId");
    Route::get("add-monthly-job-by-client-id/{client_id}", "JobLogController@addMonthlyJobByClientId")
        -> where(["client_id" => "[0-9]+"])
        -> name("addMonthlyJobByClientId");

    Route::group(["prefix" => "reporting", "as" => "reporting."], function () {
        Route::get("build", "JobLogReport\BuildReportController@build")->name("build");
        Route::get("export-report", "JobLogReport\BuildReportController@exportReport")->name("exportReport");

        /**
         * Звіти для бухгалтерії
         */
        Route::group(["prefix" => "accounting", "as" => "accounting."], function () {
            Route::get("/", "JobLogReport\AccountingReportsController@index")->name("index");
            Route::get("get-added-services/{client_id}/{month}", "JobLogReport\AccountingReportsController@getAddedServices")
                ->where(["client_id" => "[0-9]+"])
                ->name("getAddedServices");
            Route::post("download-report", "JobLogReport\AccountingReportsController@downloadReport")->name("downloadReport");
        });

    });
});

/*Translations*/
Route::resource("translations", "Translation\TranslationsController")->except(["show", "destroy"]) -> middleware("auth");
Route::group(['prefix' => "translations", 'as' => 'translations.', "middleware" => "auth"], function () {
    Route::get("destroy/{id}", "Translation\TranslationsController@destroy")->where(["id" => "[0-9]+"])->name("destroy");
});

/*Project*/
Route::resource("project", "ProjectController")->except(["show", "destroy", "store"]) -> middleware("auth");
Route::group(["prefix" => "project", "as" => "project.", "middleware" => "auth"], function () {
    Route::post("storeAjax", "ProjectController@storeAjax")->name("storeAjax");
    Route::get("close/{id}", "ProjectController@close")
        ->where(["id" => "[0-9]+"])
        ->name("close");
    Route::get("destroy/{id}", "ProjectController@destroy")
        ->where(["id" => "[0-9]+"])
        ->name("destroy");
    Route::get("details-info/{id}", "ProjectController@details_info")
        ->where(["id" => "[0-9]+"])
        ->name("details_info");
});

/**
 * Coefficient
 */
Route::resource("coefficient", "CoefficientController")->except(["show", "destroy"]) -> middleware("auth");
Route::group(["prefix" => "coefficient", "as" => "coefficient.", "middleware" => "auth"], function () {
    Route::get("destroy/{id}", "CoefficientController@destroy")
        ->where(["id" => "[0-9]+"])
        ->name("destroy");
});


/**
 * Users
 */
Route::resource("users", "UsersController")->except(["show", "destroy"]) -> middleware("auth");
Route::group(["prefix" => "users", "as" => "users.", "middleware" => "auth"], function () {
    Route::get("reset-password/{id}", "UsersController@resetPasswordForm")
        ->where(["id" => "[0-9]+"])
        ->name("resetPasswordForm");
    Route::post("reset-password/{id}", "UsersController@resetPassword")
        ->where(["id" => "[0-9]+"])
        ->name("resetPassword");
    Route::get("destroy/{id}", "UsersController@destroy")
        ->where(["id" => "[0-9]+"])
        ->name("destroy");
});

/**
 * Units
 */
Route::resource("units", "UnitsController")->except(["show", "destroy"]) -> middleware("auth");
Route::group(["prefix" => "units", "as" => "units.", "middleware" => "auth"], function () {
    Route::get("destroy/{id}", "UnitsController@destroy")
        ->where(["id" => "[0-9]+"])
        ->name("destroy");
});


Route::group(["prefix" => "zkaccess", "as" => "zkaccess.", "middleware" => "auth"], function () {
    Route::get("/", "ZKAccess\ZKAccessController@index")->name("index");
    Route::post("get-report", "ZKAccess\ZKAccessController@getReport")->name("getReport");
});

Route::group(["prefix" => "accounting", "as" => "accounting.", "middleware" => "auth"], function () {

    Route::group(["prefix" => "delivery", "as" => "delivery."],  function () {
        Route::get("/", "Accounting\DeliveryController@index") -> name("index");

        Route::get("by-qr", "Accounting\DeliveryController@byQr") -> name("byQr");

        Route::get("by-product-id/{product_id}", "Accounting\DeliveryController@byProductId") -> where(["product_id" => "[0-9]+"]) -> name("byProductId");
        Route::post("delivery-store", "Accounting\DeliveryController@deliveryStore") -> name("deliveryStore");
        Route::get("getClientWorkerByClientId/{client_id}", "Accounting\DeliveryController@getClientWorkerByClientId") -> name("getClientWorkerByClientId");

    });

    Route::group(["prefix" => "cartridge", "as" => "cartridge."], function () {
        Route::get("/", "Accounting\CartridgeAccountingController@index") -> name("index");
        Route::get("delivery-by-qr", "Accounting\CartridgeAccountingController@deliveryByQr") -> name("deliveryByQr");

        Route::get("delivery-by-product-id/{product_id}", "Accounting\CartridgeAccountingController@deliveryByProductId")
            -> where(["product_id" => "[0-9]+"])
            -> name("delivery-by-product-id");
    });
});

app/Http/Controllers/ServicesItemController.php
<?php

namespace App\Http\Controllers;

use App\Forms\ImportServicesForm;
use App\Forms\ServicesItemForm;
use App\Helpers\ControllerHelper;
use App\Imports\ServicesImport;
use App\Model\Services\ServicesItem;
use App\Repository\ClientRepository;
use App\Repository\RegistryRepository;
use App\Repository\ServicesGroupRepository;
use App\Repository\ServicesItemRepository;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\Validator;
use Kris\LaravelFormBuilder\FormBuilder;
use Maatwebsite\Excel\Facades\Excel;
use Illuminate\Support\Facades\DB;

/**
 * Class ServicesItemController
 * @package App\Http\Controllers
 */
class ServicesItemController extends Controller
{
    use ControllerHelper;

    /**
     * @var ServicesItem
     */
    private $ServicesItemModel;

    /**
     * @var ServicesItemRepository
     */
    private $ServicesItemRepository;

    /**
     * @var ServicesGroupRepository
     */
    private $ServicesGroupRepository;

    /**
     * @var ClientRepository
     */
    private $ClientRepository;

    /**
     * ServicesController constructor.
     */
    public function __construct()
    {
        $this->ServicesItemModel = app(ServicesItem::class);
        $this->ServicesItemRepository = app(ServicesItemRepository::class);
        $this->ServicesGroupRepository = app(ServicesGroupRepository::class);
        $this->ClientRepository = app(ClientRepository::class);
    }

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        $dataForTable = $this->ServicesItemRepository->getForTable();
        return view("services_item.index", [
            "title" => __("page.service.showAllItem.title"),
            "card_title" => __("page.service.showAllItem.title"),
            "dataForTable" => $dataForTable,
            "table_id" => "services_item",
            "formFilter" => [
                "services_item_client_id" => $this->ClientRepository->getForSelect(),
                "service_group_id" => $this->ServicesGroupRepository->getForSelect()
            ]
        ]);
    }

    /**
     * @param FormBuilder $formBuilder
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create(FormBuilder $formBuilder)
    {
        $form = $formBuilder->create(ServicesItemForm::class, [
            "method" => "POST",
            "url" => route("services.item.store"),
        ]);

        return view("services_item.create",
            [
                "form" => $form,
                "title" => __("page.services.item.create.title"),
                "card_title" => __("page.services.item.create.title"),
            ]
        );
    }

    /**
     * @param Request $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(Request $request)
    {
        Validator::make($request->input(), [
            "name" => "required|unique:services_item,name",
            "price" => "required",
            "unit_id" => "required|exists:units,id",
            "service_group_id" => "required|exists:services_group,id",
        ])->validate();

        $result = $this->ServicesItemModel->store($request->except(["_token"]));
        return $this->resultRedirect($result);
    }

    /**
     * @param $id
     * @param FormBuilder $formBuilder
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit($id, FormBuilder $formBuilder)
    {
        $model = RegistryRepository::services_item()->getForEdit($id);
        $form = $formBuilder->create(ServicesItemForm::class, [
            "method" => "PUT",
            "url" => route("services.item.update", $id),
            "model" => $model,
        ]);

        $servicesGroups = $this->ServicesGroupRepository
            ->getByClientId($model->client_id,["services_group.id as id", DB::raw("CONCAT_WS('',`clients`.`short_name`, ' - ' ,`services_group`.`name`) as name")])
            ->pluck("name", "id")
            ->toArray();

        $form->modify("service_group_id", "select", [
            'choices' => $servicesGroups,
            'attr' => [
                "class" => "form-control select2",
                "id" => "services_group_id"
            ],
        ], true);

        return view("services_item.update",
            [
                "form" => $form,
                "title" => __("page.services.item.update.title"),
                "card_title" => __("page.services.item.update.title"),
            ]
        );
    }

    /**
     * @param Request $request
     * @param $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(Request $request, $id)
    {
        Validator::make($request->input(), [
            "name" => "required",
            "price" => "required",
            "unit_id" => "required|exists:units,id",
            "service_group_id" => "required|exists:services_group,id",
        ])->validate();

        $result = $this->ServicesItemModel->store($request->except(["_token"]), $id);
        return $this->resultRedirect($result);
    }


    /**
     * @param $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy($id)
    {
        $result = $this->ServicesItemModel->is_deleted($id);
        return $this->resultRedirect($result);
    }

    /**
     * @param Request $request
     * @return \Illuminate\Http\JsonResponse
     */
    public function getServicesItem(Request $request)
    {
        $result = RegistryRepository::services_item()->getForCreateJob($request->id);
        $result = ($result !== NULL) ? $result->toArray() : ["null"];
        return response()->json($result);
    }

    /**
     * @param Request $request
     * @return \Illuminate\Http\JsonResponse
     */
    public function getServicesItemByClientId(Request $request)
    {
        $result = $this->ServicesItemRepository->getByClientId($request->client_id, ["id", "name as text"]);
        $result = ($result !== NULL) ? ["results" => $result->toArray(), "pagination" => ["more" => false]] : ["null"];
        return response()->json($result);
    }

    /**
     * @param FormBuilder $formBuilder
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function formImport(FormBuilder $formBuilder)
    {
        $form = $formBuilder->create(ImportServicesForm::class, [
            "method" => "POST",
            "enctype" => "multipart/form-data",
        ]);

        return view("layouts.simples.simple_form", [
            "form" => $form,
            "title" => __("page.services.import"),
            "card_title" => __("page.services.import"),
        ]);
    }

    /**
     * @param Request $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function import(Request $request)
    {
        Storage::disk("local")->putFileAs("tmp/", $request->file("xlsx_file"), "import_services.xlsx");

        $ServicesItemImport = new ServicesImport();
        $array = Excel::toArray($ServicesItemImport, 'tmp\import_services.xlsx');

        $ModelServicesItem = new ServicesItem();
        $ModelServicesItem->import($array[0]);

        return redirect()->back()->with("message", __("main.Success"));
    }
}

resources/views/services_item/create.blade.php
@extends("layouts.simples.simple_form");


@section("js")
    @parent
    {{Html::script("js/components/services_item/create.js")}}
    <script>
        $("document").ready(function () {
            check_services_group();
        });
    </script>

@stop

resources/views/services_item/index.blade.php
@extends("layouts.data_table", ["nowrap" => false])
@section("plugins.Select2", true)
@section("plugins.bootstrap4Duallistbox", true)
@section("plugins.daterangepicker", true)


@section("control_card_header")
    <div class="card-tools">
        <button type="button" class="btn btn-default btn-sm" data-card-widget="collapse"
                data-toggle="tooltip" title="Collapse">
            <i class="fas fa-minus"></i>
        </button>
    </div>
@endsection

@section("control_card")
    <div class="row">
        <div class="col-12">
            {{Form::open(["method" => "GET"])}}
            <div class="row">
                <div class="col-6">
                    <div class="form-group">
                        {{Form::label( __("form.job_log.create.attr.client_id"))}}
                        {{Form::select("services_item_client_id[]", ['' => __("form.base.attr.select_empty_val")] + $formFilter['services_item_client_id'], isset($_GET['services_item_client_id']) ? $_GET['services_item_client_id'] : null, ["class" => "form-control select2", "id" => "services_item_client_id"])}}
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-12">
                    <div class="form-group">
                        {{Form::submit("Фільтрувати", ["class" => "btn btn-info"] )}}
                        <a href="{{route("services.item.index")}}" class="btn btn-warning">Зкинути фільтри</a>
                    </div>
                </div>
            </div>
            {{Form::close()}}
        </div>
    </div>
    <div class="row">
        <div class="col-sm-12">
            <a href="{{route("services.item.create")}}" class="btn btn-success"> <i class="fa fa-plus"></i> {!! __("basic.label.add") !!} </a>
        </div>
    </div>
@endsection

@section("table_header")
    <tr>
        <th>{!! __("form.base.attr.id") !!}</th>
        <th></th>
        <th></th>
        <th>{!! __("form.service.item.attr.name") !!}</th>
        <th>{!! __("form.service.item.attr.price") !!}</th>
        <th>{!! __("form.service.item.attr.unit") !!}</th>
        <th>{!! __("form.service.item.attr.service_group") !!}</th>
        <th>{!! __("page.base.labels.isDeleted") !!}</th>
        <th>{!! __("form.job_log.create.attr.client_id") !!}</th>
        <th>{!! __("form.base.attr.created") !!}</th>
        <th>{!! __("form.base.attr.updated") !!}</th>
    </tr>
@endsection

@section("table_body")
    @foreach($dataForTable as $item)
        <tr>
            <td>{!! $item->id !!}</td>
            <td>
                <a href="{{route("services.item.edit", $item->id)}}" title="{!! __("page.basic.label.edit") !!}" class="btn btn-block btn-outline-success btn-sm "><i class="fa fa-edit"></i></a>
            </td>
            <td>
                <button data-href="{{route("services.item.destroy", "$item->id")}}" title="Видалити" class="btn btn-block btn-outline-danger btn-sm deleteItem"  ><i class="fa fa-trash"></i></button>
            </td>
            <td class="w-25">{!! $item->name !!}</td>
            <td>{!! $item->price !!}</td>
            <td>{!! $item->unit !!}</td>
            <td>{!! $item->service_group !!}</td>
            <td>
                @if($item->is_deleted)
                    <span class="badge badge-danger">{!! __("page.base.labels.yes") !!}</span>
                @else
                    <span class="badge badge-success">{!! __("page.base.labels.no") !!}</span>
                @endif
            </td>
            <td>{!! $item->client_name !!}</td>
            <td>{!! $item->created_at !!}</td>
            <td>{!! $item->updated_at !!}</td>
        </tr>
    @endforeach
@endsection

@section("table_footer")
    <tr>
        <th>{!! __("form.base.attr.id") !!}</th>
        <th></th>
        <th></th>
        <th>{!! __("form.service.item.attr.name") !!}</th>
        <th>{!! __("form.service.item.attr.price") !!}</th>
        <th>{!! __("form.service.item.attr.unit") !!}</th>
        <th>{!! __("form.service.item.attr.service_group") !!}</th>
        <th>{!! __("page.base.labels.isDeleted") !!}</th>
        <th>{!! __("form.job_log.create.attr.client_id") !!}</th>
        <th>{!! __("form.base.attr.created") !!}</th>
        <th>{!! __("form.base.attr.updated") !!}</th>
    </tr>
@endsection

@section("js")
    @parent
    <script>
        $(document).ready(function () {
            $(".select2").select2();
        });

        $(".deleteItem").on("click", function () {
            let href = $(this).attr("data-href");
            scripts.confirmDeleteItemByHref(href)
        })
    </script>
@stop

resources/views/services_item/update.blade.php
@extends("layouts.simples.simple_form");

@section("js")
    @parent
    {{Html::script("js/components/services_item/create.js")}}
@stop