routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes(["register" => false, "reset" => false]);

Route::get('/', "HomeController@index")->middleware("auth")->name("home");

/*Client*/
Route::resource("client", "ClientController")->except(["show", "destroy"]) -> middleware("auth");
Route::group(['prefix' => "client", 'as' => 'client.', "middleware" => "auth"], function () {
    Route::get("destroy/{id}", "ClientController@destroy")->where(["id" => "[0-9]+"])->name("destroy");
    Route::get("monthly-services-form/{id}", "ClientController@monthlyServicesForm")
        ->where(["id" => "[0-9]+"])
        ->name("monthlyServicesForm");

    Route::post("monthly-services-add/{id}", "ClientController@monthlyServicesAdd")
        ->where(["id" => "[0-9]+"])
        ->name("monthlyServicesAdd");

    Route::get("monthly-services-delete/{id}/{services_item_id}", "ClientController@monthlyServicesDelete")
        ->where(["id" => "[0-9]+"])
        ->where(["services_item_id" => "[0-9]+"])
        ->name("monthlyServicesDelete");
});

/*Services*/
Route::group(['prefix' => "services", 'as' => 'services.', "middleware" => "auth"], function () {
    Route::get("import", "ServicesItemController@formImport")->name("formImport");
    Route::post("import", "ServicesItemController@import")->name("import");

    /*ServicesItem*/
    Route::resource("item", "ServicesItemController")->except(["show", "destroy"]);
    Route::group(['prefix' => "item", 'as' => 'item.', "middleware" => "auth"], function () {
        Route::get("destroy/{id}", "ServicesItemController@destroy")->where(["id" => "[0-9]+"])->name("destroy");
    });

    /**
     * ServiceGroup
     */
    Route::resource("group", "ServicesGroupController")->except(["show", "destroy"]);
    Route::group(['prefix' => "group", 'as' => 'group.', "middleware" => "auth"], function () {
        Route::get("destroy/{id}", "ServicesGroupController@destroy")->where(["id" => "[0-9]+"])->name("destroy");
    });

    Route::post("getServicesItem", "ServicesItemController@getServicesItem")->name("getServicesItem");
    Route::post("getServicesItemByClientId", "ServicesItemController@getServicesItemByClientId")->name("getServicesItemByClientId");
    Route::post("getServicesGroupByClientId", "ServicesGroupController@getServicesGroupByClientId")->name("getServicesGroupByClientId");
});

/*Job-log*/
Route::group(['prefix' => "job-log", 'as' => 'job_log.', "middleware" => "auth"], function () {
    Route::get("show", "JobLogController@index")->name("index")->middleware("job_log.dataTable.defaultFilter");
    Route::get("create", "JobLogController@create")->name("create");
    Route::post("store", "JobLogController@store")->name("store");
    Route::get("update/{id}", "JobLogController@edit")->name("edit");
    Route::post("update/{id}", "JobLogController@update")->name("update");
    Route::get("delete/{id}", "JobLogController@delete")->name("delete");
    Route::post("getJobByProject", "JobLogController@getJobByProject")->name("getJobByProject");

    Route::post("calcTotalAjax", "JobLogController@calcTotalAjax")->name("calcTotalAjax");
    Route::post("checkMonthlyJobByClientId", "JobLogController@checkMonthlyJobByClientId") -> name("checkMonthlyJobByClientId");
    Route::get("add-monthly-job-by-client-id/{client_id}", "JobLogController@addMonthlyJobByClientId")
        -> where(["client_id" => "[0-9]+"])
        -> name("addMonthlyJobByClientId");

    Route::group(["prefix" => "reporting", "as" => "reporting."], function () {
        Route::get("build", "JobLogReport\BuildReportController@build")->name("build");
        Route::get("export-report", "JobLogReport\BuildReportController@exportReport")->name("exportReport");

        /**
         * Звіти для бухгалтерії
         */
        Route::group(["prefix" => "accounting", "as" => "accounting."], function () {
            Route::get("/", "JobLogReport\AccountingReportsController@index")->name("index");
            Route::get("get-added-services/{client_id}/{month}", "JobLogReport\AccountingReportsController@getAddedServices")
                ->where(["client_id" => "[0-9]+"])
                ->name("getAddedServices");
            Route::post("download-report", "JobLogReport\AccountingReportsController@downloadReport")->name("downloadReport");
        });

    });
});

/*Translations*/
Route::resource("translations", "Translation\TranslationsController")->except(["show", "destroy"]) -> middleware("auth");
Route::group(['prefix' => "translations", 'as' => 'translations.', "middleware" => "auth"], function () {
    Route::get("destroy/{id}", "Translation\TranslationsController@destroy")->where(["id" => "[0-9]+"])->name("destroy");
});

/*Project*/
Route::resource("project", "ProjectController")->except(["show", "destroy", "store"]) -> middleware("auth");
Route::group(["prefix" => "project", "as" => "project.", "middleware" => "auth"], function () {
    Route::post("storeAjax", "ProjectController@storeAjax")->name("storeAjax");
    Route::get("close/{id}", "ProjectController@close")
        ->where(["id" => "[0-9]+"])
        ->name("close");
    Route::get("destroy/{id}", "ProjectController@destroy")
        ->where(["id" => "[0-9]+"])
        ->name("destroy");
    Route::get("details-info/{id}", "ProjectController@details_info")
        ->where(["id" => "[0-9]+"])
        ->name("details_info");
});

/**
 * Coefficient
 */
Route::resource("coefficient", "CoefficientController")->except(["show", "destroy"]) -> middleware("auth");
Route::group(["prefix" => "coefficient", "as" => "coefficient.", "middleware" => "auth"], function () {
    Route::get("destroy/{id}", "CoefficientController@destroy")
        ->where(["id" => "[0-9]+"])
        ->name("destroy");
});


/**
 * Users
 */
Route::resource("users", "UsersController")->except(["show", "destroy"]) -> middleware("auth");
Route::group(["prefix" => "users", "as" => "users.", "middleware" => "auth"], function () {
    Route::get("reset-password/{id}", "UsersController@resetPasswordForm")
        ->where(["id" => "[0-9]+"])
        ->name("resetPasswordForm");
    Route::post("reset-password/{id}", "UsersController@resetPassword")
        ->where(["id" => "[0-9]+"])
        ->name("resetPassword");
    Route::get("destroy/{id}", "UsersController@destroy")
        ->where(["id" => "[0-9]+"])
        ->name("destroy");
});

/**
 * Units
 */
Route::resource("units", "UnitsController")->except(["show", "destroy"]) -> middleware("auth");
Route::group(["prefix" => "units", "as" => "units.", "middleware" => "auth"], function () {
    Route::get("destroy/{id}", "UnitsController@destroy")
        ->where(["id" => "[0-9]+"])
        ->name("destroy");
});


Route::group(["prefix" => "zkaccess", "as" => "zkaccess.", "middleware" => "auth"], function () {
    Route::get("/", "ZKAccess\ZKAccessController@index")->name("index");
    Route::post("get-report", "ZKAccess\ZKAccessController@getReport")->name("getReport");
});

Route::group(["prefix" => "accounting", "as" => "accounting.", "middleware" => "auth"], function () {

    Route::group(["prefix" => "delivery", "as" => "delivery."],  function () {
        Route::get("/", "Accounting\DeliveryController@index") -> name("index");

        Route::get("by-qr", "Accounting\DeliveryController@byQr") -> name("byQr");

        Route::get("by-product-id/{product_id}", "Accounting\DeliveryController@byProductId") -> where(["product_id" => "[0-9]+"]) -> name("byProductId");
        Route::post("delivery-store", "Accounting\DeliveryController@deliveryStore") -> name("deliveryStore");
        Route::get("getClientWorkerByClientId/{client_id}", "Accounting\DeliveryController@getClientWorkerByClientId") -> name("getClientWorkerByClientId");

    });

    Route::group(["prefix" => "cartridge", "as" => "cartridge."], function () {
        Route::get("/", "Accounting\CartridgeAccountingController@index") -> name("index");
        Route::get("delivery-by-qr", "Accounting\CartridgeAccountingController@deliveryByQr") -> name("deliveryByQr");

        Route::get("delivery-by-product-id/{product_id}", "Accounting\CartridgeAccountingController@deliveryByProductId")
            -> where(["product_id" => "[0-9]+"])
            -> name("delivery-by-product-id");
    });
});

app/Http/Controllers/JobLogReport/AccountingReportsController.php
<?php

namespace App\Http\Controllers\JobLogReport;

use App\Exports\JobLogAccountingReportExport;
use App\Exports\JobLogBuhReportExport;
use App\Http\Controllers\Controller;
use App\Repository\RegistryRepository;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use Maatwebsite\Excel\Facades\Excel;

/**
 * Class AccountingReportsController
 * @package App\Http\Controllers\JobLogReport
 */
class AccountingReportsController extends Controller
{
    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        return view("job_log.reporting.accounting_reports.index_form", [
            "title" => "Звіт для бухгалтерії",
            "formData" => [
                "month_list" => __("main.month_list"),
                "clients" => RegistryRepository::client()->getForSelect()
            ]
        ]);
    }

    /**
     * @param $client_id
     * @param null $month
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function getAddedServices($client_id, $month = null)
    {
        $data = RegistryRepository::job_log()->getByClientIdGroupServices($client_id, $month);

        $month = ($month == null) ? date("m") : $month;

        return view("job_log.reporting.accounting_reports.getAddedServices", [
            "title" => "Звіт для бухгалтерії",
            "data" => $data,
            "client_id" => $client_id,
            "month" => $month,
            "client_name" => RegistryRepository::client()->getForEdit($client_id)->name,
            "month_name" => __("main.month_list." . $month)
        ]);

    }

    /**
     * @param Request $request
     * @return \Symfony\Component\HttpFoundation\BinaryFileResponse
     */
    public function downloadReport(Request $request)
    {
        Validator::make($request->input(), ["client_id => required"])->validate();

        $model = RegistryRepository::job_log()->getForAccountingReport($request->client_id, $request->month, $request->remove_from_report);

        #dd($model->toArray());

        $export = new JobLogAccountingReportExport();
        $export->setModel($model);
        return Excel::download($export, "job_log_report.xlsx");

    }
}

resources/views/job_log/reporting/accounting_reports/getAddedServices.blade.php
@extends("layouts.page")


@section("content")

    {{Form::open(["method" => "POST", "url" => route("job_log.reporting.accounting.downloadReport")])}}

    {{Form::hidden("client_id", $client_id)}}
    {{Form::hidden("month", $month)}}

    <div class="card card-default" >
        <div class="card-header">
            <h3 class="card-title">
                Надані послуги <strong>{!! $client_name !!}</strong> за {!! $month_name !!}
            </h3>
        </div>
        <div class="card-body">
           <div class="row">
               <div class="col-12">
                    <div class="form-group">
                        {{Form::submit("Завантажити звіт без обраних послгу", ["class" => "btn btn-outline-success"])}}
                    </div>
               </div>
           </div>
           <div class="row">
               <div class="col-12">
                   <table class="table table-hover table-bordered table-sm">
                       <thead>
                       <tr>
                           <th></th>
                           <th>Назва послуги</th>
                           <th>Загальна кількість</th>
                           <th>Сума</th>
                       </tr>
                       </thead>
                       <tbody>

                       @if (!$data->isEmpty())
                           @foreach($data as $item)
                               <tr>
                                   <td>
                                       {{Form::checkbox("remove_from_report[]", $item->id)}}
                                   </td>
                                   <td>{!! $item->name !!}</td>
                                   <td>{!! $item->count !!}</td>
                                   <td>{!! $item->total_price !!}</td>
                               </tr>
                           @endforeach
                       @else

                       @endif

                       </tbody>
                   </table>
               </div>
           </div>
        </div>
    </div>
    {{Form::close()}}

@endsection()

resources/views/job_log/reporting/accounting_reports/index_form.blade.php
@extends("layouts.page")
@section('plugins.Datatables', true)
@section("plugins.daterangepicker", true)
@section("plugins.Select2", true)
@section("plugins.bootstrap4Duallistbox", true)


@section("content")

    <div class="card card-default">
        <div class="card-header">
            <h3 class="card-title">Звіт для бухгалтерії</h3>
        </div>
        <div class="card-body">

            {{Form::open(["method" => "POST", "url" => ""])}}

            <div class="row">
                <div class="col-6">
                    <div class="form-group">
                        {{Form::label("Місяць")}}
                        {{Form::select("mouth", $formData["month_list"], date("m"), ["class" => "select2", "style" => "width:100%", "id" => "month"])}}
                    </div>
                </div>
                <div class="col-6">
                    <div class="form-group">
                        {{Form::label("Клієнт")}}
                        {{Form::select("client_id", $formData["clients"], null, ["class" => "select2", "style" => "width:100%", "id" => "client_id" ])}}
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-6">
                    <div class="form-group">
                        {{Form::button("Формувати", ["class" => "btn btn-outline-success", "id" => "createReportForAccounting"])}}
                    </div>
                </div>
            </div>

            {{Form::close()}}
        </div>
    </div>

@endsection


@section("js")
    @parent
    {{Html::script("js/components/job_log/Reporting/AccountingReports/index_form.js")}}
    <script>
        $(function () {
            $(".select2").select2();
        });
    </script>

@endsection